### ISSUE TITLE
FIDO vs. IDO

### ISSUE THREAD

**Issue by crudbug** [Netflix/Fido#3]
"Fully" seams superfluous here, also as mentioned in the blog post, big confusion with FIDO Alliance. Integrated Defense Operations (IDO) or Unified Defense Operations (UDO) would be a better option.

Just a suggestion.

**Comment by Burnett01** [comment]
+support

**Comment by robfry** [comment]
I came up with the name FIDO in March of 2011 after I wrote the first version. I was looking for a project name and internally I asked people what name they wanted. Cujo was one which came out most popular, except with myself. I didn't want something which was intentioned to be protecting our network to be associated by name to a horror movie about a rabid dog. During my time at Yahoo I became good at creating projects names as acronyms, such as the DUBS framework... or distributed uninterrupted background service. Therefore, I decide to use the parallel of Cujo... except a nicer version. From there I chose words which most closely resembled what I was envisioning for the project and the name FIDO was born. 

As for the FIDO alliance... I do get a lot of crap about the name conflict from friends and colleagues. I'm a huge fan of them and internally was a big proponent for Netflix joining the FIDO alliance. However, if truth be told, I was using FIDO a full year before the FIDO alliance... they officially formed in summer of 2012. :)

I do like the UDO suggestion though... unified makes a lot of sense, but it would screw up my mojo with all the logos and stickers we've already created.

**Comment by ajs124** [comment]
I would like to mention that Udo is a german male first name.

**Comment by Burnett01** [comment]
Slunds good to me

**Comment by saqib-ali** [comment]
+1 @crudbug

**Comment by robfry** [comment]
Thank you all for the suggestions.
